# Generated by Django 4.1.7 on 2023-03-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=12)),
            ],
        ),
    ]
