# Generated by Django 4.1.7 on 2023-03-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_customuser_dt_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='local_nascimento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
